services:
  bolt:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - RUNNING_IN_DOCKER=true
      - OLLAMA_API_BASE_URL=https://ollama.intellicaai.space
      - DEFAULT_NUM_CTX=32768
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: pnpm run dockerstart
    restart: unless-stopped
